### ISSUE TITLE
@password_protected_command / @admin_command

### ISSUE THREAD

**Issue by FelixGail** [BjoernPetersen/TelegramMusicBot#35]
Decorators do not work from outside.

Example `password_protected_command`:
import will provide global variables. But at the start of the bot the password is " ". Password changes do not reach the plugins, therefore they are not usable.

This problem includes the example code in the readme.md (And i don't understand how i did not notice)

**Comment by BjoernPetersen** [comment]
I'm planning to refactor the project (especially the bot module) to make it a lot more modular in the near future. The refactoring will, among other things, solve this issue and bring issue #4 closer to resolvability.
