### ISSUE TITLE
Config path

### ISSUE THREAD

**Issue by FelixGail** [BjoernPetersen/TelegramMusicBot#38]
Python files are inside telegrammusicbot directory. Therefore the config path should be "../config"

**Comment by FelixGail** [comment]
Changing the directory is not the optimal approach.
It looks like when going to the parent directory not the "bot.py" path is important, but the path the bot was opened from (e.g calling "python path/to/bot/telegrammusicbot/bot.py" will search for "path/to/config")

**Comment by BjoernPetersen** [comment]
I understand this is an issue right now. After the next refactoring step (currently in progress) I'll probably create a main.py module in the root path to solve this...
